# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Build applicaton staging env."
  lane :build_app_staging do
    re_build_staging()
  end

  desc "Before build app"
  lane :re_build_staging do
    Dir.chdir("..")
    sh('script/re_build_staging.sh')
  end
end
