# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Build applicaton staging env."
  lane :build_app_staging do
    re_build_staging()
  end

  desc "Before build app"
  lane :re_build_staging do
    Dir.chdir("..")
    sh('script/re_build_staging.sh')
  end

  lane :build_apk do
    flutter(
      task: 'build',
      flavor: 'production',
      build_number: ENV['BUILD_NUMBER'],
      release: true,
      build_name: '1.0.0'
    )
  end 
  
  lane :bump_version do
    # Read the current version number from the pubspec.yaml file
    pubspec = YAML.load_file('../pubspec.yaml')
    current_version = pubspec['version']
  
    # Increment the patch version number
    parts = current_version.split('.')
    parts[-1] = parts[-1].to_i + 1
    new_version = parts.join('.')
  
    # Update the pubspec.yaml file with the new version number
    pubspec['version'] = new_version
    File.write('pubspec.yaml', YAML.dump(pubspec))
  
    # Commit the change
    sh "git commit -am 'Bump version to #{new_version}'"
  end
end


