# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build applicaton staging env."
  lane :build_app_staging do
    re_build_staging
    get_firebase_version_android
    build_staging
  end

  desc "Before build app"
  lane :re_build_staging do
    sh('../script/re_build_staging.sh')
  end

  lane :build_staging do
    get_firebase_version_android
    latest_release = Actions.lane_context[SharedValues::FIREBASE_APP_DISTRO_LATEST_RELEASE]
    if latest_release.nil?
      build_version = "1.0.0"
      build_number = 1
    else
      build_version = latest_release[:displayVersion] || "1.0.0"
      build_number = (latest_release[:buildVersion].to_i + 1).to_s
    end
    flutter_build(
      build: 'apk',
      build_name: build_version,
      build_number: build_number,
    )
    upload_firebase_app_distribution
  end 

  lane :get_firebase_version_android do
    desc "Get latest release firebase app distribution and increase version"
    latest_release = firebase_app_distribution_get_latest_release(
      app: ENV["FIREBASE_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
    )
  end

  lane :upload_firebase_app_distribution do
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      groups: "staging-test",
      release_notes: "Production",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_path: ENV["ANDROID_ARTIFACT_PATH"],
    )
  end

  lane :get_changelog do
    read_changelog(
      changelog_path: ENV['CHANGELOG_PATH'],
    )
  end
end